language: android
sudo: required
jdk: oraclejdk8
services:
  - docker
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/google-cloud-sdk/"
env:
  global:
    - ANDROID_API=21
    - EMULATOR_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5
android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_install:
  - yes | sdkmanager "platforms;android-28"
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true
  - openssl aes-256-cbc -K $encrypted_36a497b301fb_key -iv $encrypted_36a497b301fb_iv -in key.json.enc -out key.json -d
before_script:
  # Firebase setup
  - wget --quiet --output-document=/tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
  - tar zxf /tmp/google-cloud-sdk.tar.gz google-cloud-sdk
  - echo ./google-cloud-sdk/install.sh
  - source ./google-cloud-sdk/path.bash.inc
#  - gcloud components update
#  - gcloud components install
  - gcloud config set project modules-4b395
  - gcloud auth activate-service-account travisci@modules-4b395.iam.gserviceaccount.com --key-file key.json
#  - gcloud auth login travisci@modules-4b395.iam.gserviceaccount.com

script:
  - ./gradlew -PciBuild=true :app:assembleAndroidTest
  - gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus4,version=26,locale=en_US,orientation=portrait --timeout 20m
#  - gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --device model=Nexus4,version=21